#!/bin/bash
set -e

echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
docker push ${IMAGE}

mkdir $HOME/.aws/
cat > $HOME/.aws/credentials << END
[default]
aws_access_key_id = ${AWS_ACCESS_KEY}
aws_secret_access_key = ${AWS_SECRET_KEY}
END

STATIC_DIR=$PWD/static
mkdir -p ${STATIC_DIR}
docker run \
    --rm -v ${STATIC_DIR}:/static ${IMAGE} \
    ./manage.py collectstatic --noinput
aws \
    --endpoint-url=https://storage.yandexcloud.net \
    s3 cp --recursive ${STATIC_DIR} ${STATIC_BUCKET}

openssl \
    aes-256-cbc \
    -K $encrypted_ce0c6f32e53f_key \
    -iv $encrypted_ce0c6f32e53f_iv \
    -in keys.tar.enc \
    -out keys.tar \
    -d
tar xvf keys.tar

export DOCKER_HOST="${REMOTE_DOCKER_HOST}:2375"
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=keys

docker-compose -f compose/prod.yaml run \
    --rm server \
    bash -c './manage.py migrate && ./manage.py loaddata statuses'

docker stack deploy --prune --compose-file compose/prod.yaml phonerepair

docker system prune -f
