FROM rkashapov/remontsotik:latest

RUN apt update && apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt install -y --no-install-recommends \
        nodejs npm \
    && rm -rf /var/lib/apt/lists/*
