#!/bin/bash

BROWSER_PORT=3000
TEST_NETWORK=test-network

docker network create ${TEST_NETWORK}
docker run \
    -p ${BROWSER_PORT}:3000 \
    --name browser \
    --network ${TEST_NETWORK} \
    -d \
    browserless/chrome

docker run \
    --name test.server \
    -e DJANGO_SETTINGS_MODULE=phonerepair.config.ci \
    --expose 43923 \
    --network ${TEST_NETWORK} \
    --rm \
    ${IMAGE} \
    pytest
code=$?

[ code -ne 1 ] && docker logs browser
docker rm -f browser

exit $code
