version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/hardtechnik/data:/var/lib/postgresql/data
    deploy:
      mode: global

  server:
    image: ${IMAGE}
    depends_on:
      - postgres
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DOMAIN: ${DEPLOY_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PRIVATE_BUCKET: ${PRIVATE_BUCKET}
      SECRET_KEY: ${SECRET_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      DJANGO_SETTINGS_MODULE: phonerepair.config.prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_DB: 1
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        failure_action: rollback

  worker:
    image: ${IMAGE}
    depends_on:
      - postgres
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DOMAIN: ${DEPLOY_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PRIVATE_BUCKET: ${PRIVATE_BUCKET}
      SECRET_KEY: ${SECRET_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      DJANGO_SETTINGS_MODULE: phonerepair.config.prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_DB: 1
    command: celery -A phonerepair worker -l info
    deploy:
      replicas: 1

  letsencrypt:
    cap_add:
      - NET_ADMIN
    image: linuxserver/letsencrypt:0.36.0-ls51
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      URL: ${DEPLOY_HOST}
      SUBDOMAINS: www
      VALIDATION: http
    ports:
      - 443:443
      - 80:80
    volumes:
      - /home/hardtechnik/config:/config
    restart: unless-stopped
    deploy:
      mode: global

  redis:
    image: library/redis:5-alpine
    deploy:
      mode: global
