# Generated by Django 2.2.4 on 2019-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticketcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-ordering',), 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ('posted_at',), 'verbose_name': 'Коментарий к заявке', 'verbose_name_plural': 'Коментарии к заявке'},
        ),
        migrations.AddField(
            model_name='status',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Позиция'),
        ),
    ]
