# Generated by Django 2.2.4 on 2019-08-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(help_text='ВНИМАНИЕ! При смене статуса клиенту будет отправлен имейл', on_delete=django.db.models.deletion.PROTECT, to='core.Status', verbose_name='Статус'),
        ),
    ]
